name: Verify & Create GitHub Secrets

on:
  workflow_dispatch:
    inputs:
      target:
        description: "repo or org"
        required: true
        default: "repo"
      secret_name:
        description: "Secret name"
        required: true

jobs:
  secrets:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      actions: write

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq python3 python3-pip

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install pynacl

      - name: Verify / create secret
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TARGET: ${{ inputs.target }}
          OWNER: Nightwing-77
          REPO: mifos-x-actionhub
          SECRET_NAME: ${{ inputs.secret_name }}
          SECRET_VALUE: ${{ secrets.SECRET_VALUE_TO_SYNC }}
        run: |
          chmod +x .github/workflows/verify-secrets.sh
          .github/workflows/verify-secrets.sh